### ISSUE TITLE
Build an endpoint to find similar bookmarks 

### ISSUE THREAD

**Issue by joshlong** [the-trump-dump/editor-api#6]
E.G: given a bookmark ID or a bookmark text, find any bookmark that: 
* had the same description 
* had the same URL if you strip http and https off
* is the same URL if you lowercase both of them (for YouTube videos)
* resolved to the same URL. This might be harder. Something would need to visit each URL and see if it’s a) a redirect b) still there. It will be critical to timeout when required

**Comment by theTrumpDump** [comment]
not required, it turns out. closing.
